#!/bin/sh -e

./bootstrap.sh build
./build/muon \
    setup build
ninja -C build

mkdir -p \
    "$1/usr/bin" \
    "$1/usr/share/man/man1" \
    "$1/usr/share/man/man5"

cp build/muon               "$1/usr/bin/"
cp build/doc/muon.1         "$1/usr/share/man/man1/"
cp build/doc/meson.build.5 "$1/usr/share/man/man5/"
