#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DURIPARSER_BUILD_TESTS=OFF \
    -DURIPARSER_BUILD_DOCS=OFF

cmake --build   build
cmake --install build
