#!/bin/sh -e

patch -p1 < fix_build.patch

for f in string_entry.c button.c dialog.c drawing.c drawingP.h grabpix.c list.c \
    menu.c scrollbar.c toggle.c; do
    sed 's/Xaw3dxft/Xaw/g' "src/$f" >_
    mv _ "src/$f"
done

./configure \
    --prefix=/usr

make -j1
make DESTDIR="$1" install

mkdir -p \
    "$1/usr/share/docs/libsx/html" \
    "$1/usr/share/docs/libsx/text"
cp -R docs/* "$1/usr/share/docs/libsx/"
