#!/bin/sh -e

sed 's/build) op_test/build) /;/op_test$/d' boot-strap >_
mv _ boot-strap

export CFLAGS="$CFLAGS -static"
export LDFLAGS="$LDFLAGS -static"

sh ./boot-strap \
    --with-default-sys-path=/usr/share/mk \
    op=build

INSTALL=install \
sh ./boot-strap \
    --prefix=/usr \
    --with-mksrc=/usr/share/mk \
    --install-destdir="$1" \
    op=install

chmod 755   "$1/usr/bin/bmake"

rm -rf      "$1/usr/share/man/cat1"
mkdir -p    "$1/usr/share/man/man1/" "$1/usr/share/licenses/bmake/"

cp bmake.1  "$1/usr/share/man/man1/bmake.1"
ln -s bmake "$1/usr/bin/make"
cp LICENSE  "$1/usr/share/licenses/bmake/bmake.license"
