#!/bin/sh -e

cd bmake

sed -i 's/build) op_test/build) /' boot-strap
sed -i '/op_test$/d' boot-strap

export CFLAGS="$CFLAGS -static"
export LDFLAGS="$LDFLAGS -static"

./boot-strap \
    --with-default-sys-path=/usr/share/mk \
    op=build

INSTALL=install \
./boot-strap \
    --prefix=/usr \
    --with-mksrc=/usr/share/mk \
    --install-destdir="$1" \
    op=install

chmod 755   "$1/usr/bin/bmake"

rm -rf      "$1/usr/share/man/cat1"
mkdir -p    "$1/usr/share/man/man1/"
cp bmake.1  "$1/usr/share/man/man1/bmake.1"
ln -s bmake "$1/usr/bin/make"
mkdir -p    "$1/usr/share/licenses/bmake/"
cp LICENSE  "$1/usr/share/licenses/bmake/bmake.license"
