#!/bin/sh -e

# yes, I had a hard time with this one.
# my depends file can be cleaned up a LOT
# (configure automatically adds components based on what's available!)
# but I haven't got around to it yet.
# Also almost all of the below stuff can go.

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-perl-plugin \
    --enable-crash-dialog \
    --disable-libtool-lock \
    --disable-largefile \
    --disable-rpath \
    --disable-nls \
    --disable-manual \
    --disable-libsm \
    --disable-ipv6 \
    --disable-enchant \
    --disable-compface \
    --disable-pthread \
    --disable-startup-notification \
    --disable-dbus \
    --disable-ldap \
    --disable-jpilot \
    --disable-networkmanager \
    --disable-valgrind \
    --disable-svg \
    --disable-deprecated \
    --enable-pgpmime-plugin

# currently, setting an encryption option in an outgoing email causes a segfault.
# (for me)
# everything else works though.


make
make DESTDIR="$1" install
