#!/bin/sh -e

# all this mess is to avoid asciidoctor, whatever it is.
sed -i 's/^ASCIIDOCTOR=asciidoctor/ASCIIDOCTOR=:/' Makefile
make prefix=/usr DESTDIR="$1" \
    install-icon \
    install-examples \
    install-podboat \
    install-newsboat

# pre-generated :)
install -Dm644 -t "$1/usr/share/man/man1" \
    newsboat.1 podboat.1

DOCDIR="$1/usr/share/doc/newsboat"

install -Dm644 -t "$DOCDIR" CHANGELOG.md
install -Dm644 -t "$DOCDIR/contrib" contrib/README.md
install -Dm755 -t "$DOCDIR/contrib" \
    contrib/*.sh \
    contrib/*.rb \
    contrib/*.pl \
    contrib/*.py
install -Dm644 -t "$DOCDIR/contrib/colorschemes" \
    contrib/colorschemes/*
install -Dm755 -t "$DOCDIR/contrib/getpocket.com" \
    contrib/getpocket.com/*.sh
install -Dm644 -t "$DOCDIR/contrib/getpocket.com" \
    contrib/getpocket.com/*.md
install -Dm755 -t "$DOCDIR/contrib/image-preview" \
    contrib/image-preview/vifmimg \
    contrib/image-preview/nbrun \
    contrib/image-preview/nbparser
install -Dm644 -t "$DOCDIR/contrib/image-preview" \
    contrib/image-preview/README.org
