name: Shellcheck
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run shellcheck
        run: |
          find . -type f -name build -o -name post-install | sed 's/[^[:alnum:]]/\\&/g' | xargs shellcheck
